theme: jekyll-theme-minimal
show_downloads: false
title: Food Cost Calculator
description: Easy to use ultimate food cost calculator for chefs, freelancing caterers or anyone who need to calculate real cost of their dishes.
logo:  https://user-images.githubusercontent.com/70368829/118404237-ba222f80-b67a-11eb-90c6-c50035c0cc58.png
