name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout GIT
        uses: actions/checkout@v4

      - name: Setup Java SDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'
          
      - name: Setup google services
        run: |
          echo "$GOOGLE_SERVICES" > ./app/google-services.json
        shell: bash
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        working-directory: ./
        run: ./gradlew build

      - name: Upload Build Failure Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-failure-reports
          path: app/build/reports/

      - name: Unit Test
        working-directory: ./
        run: ./gradlew test

      - name: Upload Test Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: app/build/reports/tests/
