name: Release to internal testing

on:
  workflow_dispatch:
  push:
    branches:
      - master
env:
  repository_name: FoodCostCalculator
  playstore_name: erdees

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Setup google services
        run: |
          echo "$GOOGLE_SERVICES" > ./app/google-services.json
        shell: bash
        env:
          GOOGLE_SERVICES: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Create version code
        id: version_code
        run: echo "versionCode=$((40 + $GITHUB_RUN_NUMBER))" >> $GITHUB_ENV

      - name: Create version name
        id: version_name
        run: echo "versionName=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - uses: android-actions/setup-android@v2

      - name: Setup build tool version variable
        shell: bash
        run: |
          BUILD_TOOL_VERSION=$(ls /usr/local/lib/android/sdk/build-tools/ | tail -n 1)
          echo "BUILD_TOOL_VERSION=$BUILD_TOOL_VERSION" >> $GITHUB_ENV
          echo Last build tool version is: $BUILD_TOOL_VERSION

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-29-google-apis-x86_64

      - name: Create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Run Android Tests Before Deployment
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          target: google_apis
          arch: x86_64
          profile: Nexus 6
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedAndroidTest --no-daemon

      - name: Upload Android Test Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: android-test-reports
          path: app/build/reports/androidTests/

      - name: Build with Gradle
        working-directory: ./
        run: ./gradlew --no-daemon bundleRelease -PversionCode=${{ env.versionCode }} -PversionName=${{ env.versionName }}

      - name: Sign AAB
        uses: r0adkll/sign-android-release@v1
        id: prod_build
        with:
          releaseDirectory: ./app/build/outputs/bundle/release/
          signingKeyBase64: ${{ secrets.ANDROID_KEYSTORE_BASE_64_NEW }}
          alias: ${{ secrets.ANDROID_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: ${{ env.BUILD_TOOL_VERSION }}

      - name: Release to internal testing
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT }}
          packageName: com.erdees.foodcostcalc
          releaseFiles: ./app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: completed
          mappingFile: ./app/build/outputs/mapping/release/mapping.txt
          debugSymbols: ./app/build/intermediates/merged_native_libs/release/mergeReleaseNativeLibs/out/lib
